# **NumPy**


In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

### ***Arreglos***


In [3]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [4]:
arr = np.array(([1,2,3],[4,5,6]))
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
arr=np.array([1,2,3,4,5,6] , ndmin=3)
print(arr.ndim)
print(arr)
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])

3
[[[1 2 3 4 5 6]]]
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
1


In [7]:
arr = np.zeros([2,2])
print(arr)

[[0. 0.]
 [0. 0.]]


In [8]:
arr = np.ones([3,3])
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
arr = np.random.rand(3,3)
print(arr)

[[0.25764755 0.30132431 0.43656663]
 [0.11830633 0.04509978 0.28460134]
 [0.42528815 0.52915667 0.87564711]]


# ***Operaciones***

In [11]:
arr1=[1,2,3]
arr2 = [4,5,6]
arr3 = np.add(arr1,arr2) #suma

print(arr3)

[5 7 9]


In [12]:
arr2 = [1,2,3]
arr1 = [4,5,6]
arr3 = np.subtract(arr1,arr2) #resta
print(arr3)

[3 3 3]


In [13]:
arr1=[1,2,3]
arr2 = [4,5,6]
arr3 = np.multiply(arr1,arr2) #multiplicacion

print(arr3)

[ 4 10 18]


In [14]:
arr1=[1,2,3]
arr2 = [4,5,6]
arr3 = np.divide(arr2,arr1) #division

print(arr3)

[4.  2.5 2. ]


# ***Agregacion***

In [15]:
arr = [1,5,7]
media= np.mean(arr)
print(media)

4.333333333333333


In [16]:
arr = [1,5,7]
mediana = np.median(arr)
print(mediana)

5.0


In [17]:
arr = [1,5,7]
maximo = np.max(arr)
print(maximo)

7


In [18]:
arr = [1,5,7]
minimo = np.min(arr)
print(minimo)

1


# ***Indexación***

In [19]:
arr = np.array([1,2,3,4,5,6])
print(arr[0])

1


In [20]:
arr = np.array([1,2,3,4,5,6])
print(arr[-1]) #regresa ultimo elemento de la lista

6


In [21]:
arr = np.array(([1,2,3],[4,5,6]))
print(arr[1,2])

6


# ***Slicing***

In [22]:
arr = np.array([1,2,3,4,5,6])
print(arr[1:4])

[2 3 4]


In [23]:
arr = np.array([1,2,3,4,5,6])
print(arr[1:4:2])

[2 4]


In [24]:
arr = np.array([1,2,3,4,5,6])
print(arr[::2])

[1 3 5]


In [25]:
print("hi")

hi
